version: '3.8'

services:
  claude-dev:
    image: node:18
    container_name: claude-dev
    volumes:
      # Controlled mount points for file access
      - claude_workspace:/workspace
      # Mount only specific user directories that need to be accessed
      - ${HOME}/Desktop:/mnt/desktop:ro
      - ${HOME}/Downloads:/mnt/downloads:ro
      - ${HOME}/Documents:/mnt/documents:ro
      # Mount MCP configuration
      - ${HOME}/AppData/Roaming/Code/User/globalStorage/saoudrizwan.claude-dev/settings:/app/settings:ro
    environment:
      - NODE_ENV=production
      # Restrict permissions
      - CLAUDE_WORKSPACE=/workspace
      - DESKTOP_PATH=/mnt/desktop
      - DOWNLOADS_PATH=/mnt/downloads
      - DOCUMENTS_PATH=/mnt/documents
    networks:
      - claude_net
    security_opt:
      - no-new-privileges:true
    # Restrict capabilities
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    # Resource limits
    mem_limit: 2g
    cpus: 1.0

  claude-desktop:
    image: node:18
    container_name: claude-desktop
    volumes:
      - claude_workspace:/workspace
      # Mount only specific user directories that need to be accessed
      - ${HOME}/Desktop:/mnt/desktop:ro
      - ${HOME}/Downloads:/mnt/downloads:ro
      - ${HOME}/Documents:/mnt/documents:ro
      # Mount Claude desktop config
      - ${HOME}/AppData/Roaming/Claude:/app/claude-config:ro
    environment:
      - NODE_ENV=production
      # Restrict permissions
      - CLAUDE_WORKSPACE=/workspace
      - DESKTOP_PATH=/mnt/desktop
      - DOWNLOADS_PATH=/mnt/downloads
      - DOCUMENTS_PATH=/mnt/documents
    networks:
      - claude_net
    security_opt:
      - no-new-privileges:true
    # Restrict capabilities
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    # Resource limits
    mem_limit: 2g
    cpus: 1.0

networks:
  claude_net:
    driver: bridge
    internal: true

volumes:
  claude_workspace:
    driver: local
